### ISSUE TITLE
Implement and Discuss Conversion to Go Modules

### ISSUE THREAD

**Issue by quaggoth** [ncr-devops-platform/nagiosfoundation#137]
Referring to the blog post [Using Go Modules](https://blog.golang.org/using-go-modules), I've converted and experimented with using Go Modules instead of our currently used [Dep](https://github.com/golang/dep) tool to manage our dependencies. Based on that experience, I am recommending we switch to Go Modules.

This issue and follow-up pull request is intended to provide an area for discussing this conversion, along with live code for anyone that wishes to experiment with the changes.

### Advantages
- Uses the native Go installation and toolchain rather than requiring a developer to install Dep and execute an extra command to retrieve dependencies.
- Using this native toolchain eliminates four steps from performing a first build, making the first build as simple as 1) clone 2) change directory 3) make.
- More straightforward first-time builds makes for a smoother first-time developer and contributor experience which hopefully translates to more contributors.
- For a developer that has minimal Go experience, this also seems to eliminate the need to configure and comprehend a Go Workspace at the very beginning.
- As stated in "[Using Go Modules](https://blog.golang.org/using-go-modules)",  _Go modules are the future of dependency management in Go._
- Dep, our current dependency management tool is changing anyway. From the [README on GitHub](https://github.com/golang/dep/blob/master/README.md), ..."_we are continuing development of dep, but gearing work primarily towards the development of an alternative prototype for versioning behavior in the toolchain._"

### Disadvantages
- Go 1.1[12] use the old `vendor/` directory method by default. This is incompatible with working on the `nagiosfoundation` project in a Go Workspace. To overcome this, the developer must execute `export GO111MODULE=on` or add `GO111MODULE=on` to the front of many `go` (and gödel) commands. For example, `go build` becomes `GO111MODULE=on go build`. However, working on the `nagiosfoundation` project outside of a Go Workspace "just works" without this environment variable. When Go 1.13 is released this environment variable will no longer be needed.
- The previous point means the `Makefile` must be changed to add the `GO111MODULE` environment variable. It can be removed once 1.13 is released. Because builds are generally done with `make`, the developer won't see most of this.

Realize that all the disadvantages are never seen by a developer if the project is cloned to a directory _outside the Go Workspace_.

My experience with Go Modules is less than a day so some of these points may not be totally accurate. Feel free to correct me.

**Comment by jkerry** [comment]
I'll 👍 this.  Should we hold out until 1.13 is released before picking it up since it isn't critical path?

**Comment by jk185160** [comment]
Implemented in #194
