### ISSUE TITLE
HTTP Check should support a separate ip / hostname

### ISSUE THREAD

**Issue by jkerry** [ncr-devops-platform/nagiosfoundation#180]
When we want to test HTTP endpoints it's a fairly common need to test a local endpoint but simulate a hostname / dns retrieval to get there. The http check should be able to accept a --host field beyond the url to override the HTTP host header.

**Comment by quaggoth** [comment]
For whoever makes this addition, see [this discussion on adding a Host header](https://github.com/golang/go/issues/7682) for background on why `Header.Add("Host"...)` may not work and you may instead want to use something like `req.Host = "example.com"` such as what is in [this example](https://play.golang.org/p/DEFLb7_WRJ).

**Comment by jkerry** [comment]
closing due to #187
