### ISSUE TITLE
HTTP check should support ssl_no_verify

### ISSUE THREAD

**Issue by jkerry** [ncr-devops-platform/nagiosfoundation#181]
in order to test internal certificate endpoints where SSL certs might not match the external facing certificate / hostname http check should support a --ssl_no_verify flag

**Comment by quaggoth** [comment]
Note the `curl` utility uses `--insecure` or `-k` to specify this and `wget` uses `--no-check-certificate`. We might want to consider using one of these to try to keep consistent with other widely used utilities.

...or just go with `--ssl_no_verify`.
