### ISSUE TITLE
Check Performance Counter accepting multiple inputs

### ISSUE THREAD

**Issue by gs185220** [ncr-devops-platform/nagiosfoundation#190]
Initially, check performance counter accepts a single command and gives the values for the specified command. The changes made in this attached PR will allow the performance counter to accept multiple inputs in an array and it will display the values for all the commands specified. An example for how we pass values to the check performance counter is shown in the Readme.md file. This basically helps us in getting all the required data by making use of a single check instead of writing single check for each and every command. This performance counter doesn't compare the warning and critical values, it just displays data, mainly used for data retrieval.
PR raised for this is: https://github.com/ncr-devops-platform/nagiosfoundation/pull/189
![image](https://user-images.githubusercontent.com/66779959/94171419-dfc1b500-feae-11ea-99ef-1739cb0420a5.png)

**Comment by jkerry** [comment]
closed via #189
